backend:
  name: github
  repo: visionpopular/vision-popular
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "_posts"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "content", widget: "text" }
